[env:CDEBYTE_E77-MBL]
extends = stm32_base
board = cubecell_board_pro
board_upload.maximum_size = 233472 ; reserve the last 28KB for filesystem
board_level = extra
build_flags =
  ${stm32_base.build_flags}
  -Ivariants/ASR6601/E78-400M22S1C
  -DSERIAL_UART_INSTANCE=2
  -DPIN_SERIAL_RX=PA3
  -DPIN_SERIAL_TX=PA2
  -DENABLE_HWSERIAL1
  -DPIN_SERIAL1_RX=PB7
  -DPIN_SERIAL1_TX=PB6
  -DMESHTASTIC_EXCLUDE_ENVIRONMENTAL_SENSOR=1
  -DMESHTASTIC_EXCLUDE_I2C=1
  -DMESHTASTIC_EXCLUDE_GPS=1

upload_port = stlink